# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'LuaFix' do
pod 'wax', :git=>'https://github.com/alibaba/wax.git', :tag=>'1.1.0'
end

target 'LuaFixTests' do

end

target 'LuaFixUITests' do

end

